name: Rust

on:
    push:
      branches:
      - master
    pull_request:
      branches:
      - "**"

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

jobs:
  bulid-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fmt
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --release --verbose
    - name: Test
      run: cargo test --release --verbose
    - name: Doc
      run: cargo doc
